steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'app:latest', '--destination=asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['--destination=asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']