steps:
  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    args:
      - '--destination=asia.gcr.io/$PROJECT_ID/invoicemudah:latest'
      - '--destination=asia.gcr.io/$PROJECT_ID/invoicemudah:$SHORT_SHA'
      - '--cache=true'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'invoicemudah'
      - '--image'
      - 'asia.gcr.io/$PROJECT_ID/invoicemudah:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'